// Copyright 2025 Yubico AB
//
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using System.Formats.Cbor;
using System.Globalization;
using System.Security.Cryptography.X509Certificates;
using Yubico.YubiKey.Cryptography;
using Yubico.YubiKey.Fido2.Cbor;
using Yubico.YubiKey.Fido2.Cose;

namespace Yubico.YubiKey.Fido2
{
    /// <summary>
    /// Contains the data returned by the YubiKey after making a credential.
    /// </summary>
    /// <remarks>
    /// When a new credential is made, the YubiKey returns data about that
    /// credential, including attestation information. There are several elements
    /// in this data and this structure contains those elements.
    /// </remarks>
    public class MakeCredentialData
    {
        private const int KeyFormat = 1;
        private const int KeyAuthData = 2;
        private const int KeyAttestationStatement = 3;
        private const int KeyEnterpriseAttestation = 4;
        private const int KeyLargeBlob = 5;

        private const int MaxAttestationMapCount = 3;

        private const string AlgString = "alg";
        private const string SigString = "sig";
        private const string X5cString = "x5c";

        /// <summary>
        /// The attestation statement format identifier.
        /// </summary>
        public string Format { get; }

        /// <summary>
        /// The object that contains both the encoded authenticator data, which
        /// is to be used in verifying the attestation statement, and the decoded
        /// elements, including the credential itself, a public key.
        /// </summary>
        /// <remarks>
        /// Save the public key in this object and use it to verify assertions
        /// returned by calling <c>GetAssertion</c>.
        /// </remarks>
        public AuthenticatorData AuthenticatorData { get; }
        
        /// <summary>
        /// The algorithm used to create the attestation statement.
        /// </summary>
        public CoseAlgorithmIdentifier AttestationAlgorithm { get; private set; }

        /// <summary>
        /// The signature that is the attestation statement, which can be used to
        /// verify that the public key credential was generated by the YubiKey.
        /// This is an optional element so it can be null.
        /// </summary>
        /// <remarks>
        /// Use the public key in the zero'th element of the
        /// <see cref="AttestationCertificates"/> to verify this signature. If no
        /// attestation certificate is provided, the authenticator assumes the
        /// entity that must verify the signature will have access to the
        /// appropriate cert.
        /// <para>
        /// The data to verify is the <see cref="AuthenticatorData"/>
        /// concatenated with the client data hash (from the
        /// <see cref="MakeCredentialParameters"/>).
        /// </para>
        /// </remarks>
        public ReadOnlyMemory<byte> AttestationStatement { get; private set; }

        /// <summary>
        /// The encoded CBOR map that describes the attestation statement.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The other members of this class make it easy to access the individual
        /// elements of the attestation statement and supporting structures. This
        /// property returns the raw, CBOR encoded attestation statement returned
        /// by the YubiKey. This is useful if you are implementing or interoperating
        /// with the WebAuthn data types. It is often easier to copy this field
        /// over in its encoded form rather than using the parsed properties.
        /// </para>
        /// <para>
        /// For example: the WebAuthn MakeCredential operation expects an "attestation
        /// object" be returned. This is a CBOR map containing the "format", "attStmt",
        /// and "authData" - the keys given in string form. The "authData" is the CBOR
        /// encoded <see cref="AuthenticatorData"/> further encoded in Base64URL. The
        /// "attStmt" is the CBOR map that contains the <see cref="AttestationAlgorithm"/>,
        /// <see cref="AttestationStatement"/>, and <see cref="AttestationCertificates" />.
        /// </para>
        /// <para>
        /// Rather than reconstructing the CBOR map, we provide it here for you, already
        /// in encoded form.
        /// </para>
        /// </remarks>
        public ReadOnlyMemory<byte> EncodedAttestationStatement { get; private set; }

        /// <summary>
        /// This array contains the certificate for the public key that can be
        /// used to verify that the attestation statement, and possibly CA
        /// certificates that chain to a root. This is an optional element so it
        /// can be null.
        /// </summary>
        /// <remarks>
        /// The first cert in this list (<c>AttestationCertificates[0]</c>) will
        /// be the certificate that contains the public key that will verify the
        /// <see cref="AttestationStatement"/>. The data to verify is the
        /// <see cref="AuthenticatorData"/> concatenated with the client data
        /// hash (from the <see cref="MakeCredentialParameters"/>).
        /// </remarks>
        public IReadOnlyList<X509Certificate2>? AttestationCertificates { get; private set; }

        /// <summary>
        /// Indicates whether an enterprise attestation was returned. This is an
        /// optional value, so if the YubiKey did not return this element, the
        /// property will be null.
        /// </summary>
        /// <remarks>
        /// If there is no enterprise attestation entry in the response (this
        /// property is null), or if there was (this property is not null) and it
        /// is <c>false</c>, then there was no enterprise attestation statement
        /// returned. If there was an entry (this property is not null) and the
        /// value is <c>true</c>, then there was an enterprise attestation
        /// statement returned.
        /// </remarks>
        public bool? EnterpriseAttestation { get; private set; }

        /// <summary>
        /// If this is not null, it is the large blob key (see section 12.3 of
        /// the CTAP2 standard). This is an optional element so it can be null.
        /// </summary>
        public ReadOnlyMemory<byte>? LargeBlobKey { get; private set; }


        /// <summary>
        /// This returns the raw CBOR encoded credential data from the YubiKey, as returned by the MakeCredential operation.
        /// </summary>
        public ReadOnlyMemory<byte> RawData { get; }

        // The default constructor explicitly defined. We don't want it to be
        // used.
        private MakeCredentialData()
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Build a new instance of <see cref="MakeCredentialData"/> based on the
        /// given CBOR encoding.
        /// </summary>
        /// <remarks>
        /// The encoding must follow the definition of
        /// <c>authenticatorMakeCredential response structure</c> in section
        /// 6.1.2 of the CTAP 2.1 standard.
        /// </remarks>
        /// <param name="cborEncoding">
        /// The credential data, encoded following the CTAP 2.1 and CBOR (RFC
        /// 8949) standards.
        /// </param>
        /// <exception cref="Ctap2DataException">
        /// The <c>cborEncoding</c> is not a valid CBOR encoding, or it is not a
        /// correct encoding for FIDO2 credential data.
        /// </exception>
        public MakeCredentialData(ReadOnlyMemory<byte> cborEncoding)
        {
            RawData = cborEncoding;
            var map = new CborMap<int>(RawData);
            
            try
            {
                Format = map.ReadTextString(KeyFormat);
                AuthenticatorData = new AuthenticatorData(map.ReadByteString(KeyAuthData));

                // The credential public key is either an elliptic-curve key (classical algorithms)
                // or an ML-DSA key (post-quantum). Both are supported; anything else is unknown.
                bool isEc = AuthenticatorData.CredentialPublicKey is CoseEcPublicKey
                    && AuthenticatorData.CredentialPublicKey.Type == CoseKeyType.Ec2;
                bool isMlDsa = AuthenticatorData.CredentialPublicKey is CoseMlDsaPublicKey
                    && AuthenticatorData.CredentialPublicKey.Type == CoseKeyType.Akp;

                if ((!isEc && !isMlDsa)
                    || !map.Contains(KeyAttestationStatement)
                    || !ReadAttestation(map))
                {
                    throw new Ctap2DataException(ExceptionMessages.Ctap2UnknownAttestationFormat);
                }
                
                if (map.Contains(KeyEnterpriseAttestation))
                {
                    EnterpriseAttestation = map.ReadBoolean(KeyEnterpriseAttestation);
                }
                
                if (map.Contains(KeyLargeBlob))
                {
                    LargeBlobKey = map.ReadByteString(KeyLargeBlob);
                }
            }
            catch (CborContentException cborException)
            {
                throw new Ctap2DataException(
                    string.Format(
                        CultureInfo.CurrentCulture,
                        ExceptionMessages.InvalidFido2Info),
                    cborException);
            }
        }

        // We're expecting a Format of "packed", which means the data in the
        // key/value pair for KeyAttestationStatement is a map with 2 or 3
        // elements:
        //    "alg"/-7
        //    "sig"/byte array
        //       and possibly
        //    "x5c"/array of certs.
        // For ECDSA the signature byte array is the DER encoding; for ML-DSA it is the raw FIPS 204
        // signature. A self-attestation statement has only "alg" and "sig" (no "x5c").
        // If everything works, return true. Otherwise, return false.
        private bool ReadAttestation(CborMap<int> map)
        {
            var attestCborMap = map.ReadMap<string>(KeyAttestationStatement);
            EncodedAttestationStatement = attestCborMap.Encoded;
            if (!Format.Equals(AttestationFormats.Packed, StringComparison.Ordinal) || !attestCborMap.Contains(AlgString) ||
                !attestCborMap.Contains(SigString) ||
                attestCborMap.Count > MaxAttestationMapCount ||
                (attestCborMap.Count == MaxAttestationMapCount && !attestCborMap.Contains(X5cString)))
            {
                return false;
            }

            AttestationAlgorithm = (CoseAlgorithmIdentifier)attestCborMap.ReadInt32(AlgString);
            AttestationStatement = attestCborMap.ReadByteString(SigString);

            if (attestCborMap.Contains(X5cString))
            {
                var certList = attestCborMap.ReadArray<byte[]>(X5cString);
                var attestationCertificates = new List<X509Certificate2>(certList.Count);

                for (int index = 0; index < certList.Count; index++)
                {
                    attestationCertificates.Add(X509CertificateLoader.LoadCertificate(certList[index]));
                }

                AttestationCertificates = attestationCertificates;
            }

            return true;
        }

        /// <summary>
        /// Verify the <see cref="AttestationStatement"/> (the signature) over the
        /// <c>AuthenticatorData</c> and client data hash.
        /// </summary>
        /// <remarks>
        /// <para>
        /// If the attestation statement includes a certificate chain
        /// (<see cref="AttestationCertificates"/>), the signature is verified with the public key in
        /// the zero'th (leaf) certificate. If there is no certificate chain (self-attestation), the
        /// signature is verified with the credential's own public key
        /// (<see cref="AuthenticatorData.CredentialPublicKey"/>); this is the form used by ML-DSA
        /// credentials.
        /// </para>
        /// <para>
        /// If the signature verifies, this method returns <c>true</c>; if it does not verify, it
        /// returns <c>false</c>.
        /// </para>
        /// </remarks>
        /// <param name="clientDataHash">
        /// The client data hash sent to the YubiKey to make the credential.
        /// </param>
        /// <returns>
        /// A boolean, <c>true</c> if the attestation statement (the signature)
        /// verifies, <c>false</c> otherwise.
        /// </returns>
        /// <exception cref="InvalidOperationException">
        /// There is neither an attestation certificate nor a credential public key to verify with.
        /// </exception>
        public bool VerifyAttestation(ReadOnlyMemory<byte> clientDataHash)
        {
            // The signed data is the concatenation authenticatorData || clientDataHash.
            byte[] encodedAuthData = AuthenticatorData.EncodedAuthenticatorData.ToArray();
            byte[] message = new byte[encodedAuthData.Length + clientDataHash.Length];
            Buffer.BlockCopy(encodedAuthData, 0, message, 0, encodedAuthData.Length);
            clientDataHash.Span.CopyTo(message.AsSpan(encodedAuthData.Length));

            // Self-attestation (no x5c): the attestation signature is made with the credential's own
            // private key, so verify it with the credential public key.
            if (AttestationCertificates is null || AttestationCertificates.Count == 0)
            {
                CoseKey credentialPublicKey = AuthenticatorData.CredentialPublicKey
                    ?? throw new InvalidOperationException(ExceptionMessages.MissingCtap2Data);

                // ML-DSA verifies the message directly in "pure" mode (no pre-hash).
                if (CoseKeyHelpers.IsMlDsaAlgorithm(AttestationAlgorithm))
                {
                    using var mlDsaVfy = new MlDsaVerify(credentialPublicKey);
                    return mlDsaVfy.VerifyData(message, AttestationStatement.ToArray());
                }

                using var selfDigester = CryptographyProviders.Sha256Creator();
                using var ecdsaSelfVfy = new EcdsaVerify(credentialPublicKey);
                return ecdsaSelfVfy.VerifyDigestedData(
                    selfDigester.ComputeHash(message), AttestationStatement.ToArray());
            }

            // Full attestation: verify with the public key in the leaf attestation certificate.
            using var digester = CryptographyProviders.Sha256Creator();
            using var ecdsaVfy = new EcdsaVerify(AttestationCertificates[0]);
            return ecdsaVfy.VerifyDigestedData(
                digester.ComputeHash(message), AttestationStatement.ToArray());
        }
    }
}
